# Generated by Django 3.1.5 on 2021-01-07 23:09

from django.db import migrations

from django.utils import timezone

from datetime import timedelta


def add_row(apps, schema_editor):
    Student = apps.get_model("example", "Student")
    student = Student(last_name="Sokolov", first_name="Lev")
    student.save()

    Teacher = apps.get_model("example", "Teacher")
    teacher = Teacher(last_name="Shadrin", first_name="Daniil")
    teacher.save()

    Homework = apps.get_model("example", "Homework")
    homework = Homework(
        text="I have done this hw.", deadline=timedelta(days=3), created=timezone.now()
    )
    homework.save()

    HomeworkResult = apps.get_model("example", "HomeworkResult")
    homework_result = HomeworkResult(
        homework=homework,
        solution="I have done this hw.",
        author=student,
        created=timezone.now(),
    )
    homework_result.save()


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_row),
    ]
